"""
PDF export for the /paper agent.

Converts the Markdown draft from the Synthesis node into a clean,
print-ready PDF using fpdf2.

Design decisions:
- Uses a Unicode-capable core font (Helvetica / built-in) to avoid
  needing to ship TTF files in the repo.
- Renders Markdown headings (##, ###), bold text (**...**), bullet
  points, horizontal rules, and plain paragraphs.
- Page header includes the paper title; footer includes the CDLI
  attribution and auto page number.
"""

import re
from pathlib import Path

from fpdf import FPDF

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MARGIN = 18          # mm
LINE_HEIGHT = 6      # mm per text line
TITLE_SIZE = 18
H2_SIZE = 14
H3_SIZE = 12
BODY_SIZE = 10
FOOTER_SIZE = 8
PAGE_WIDTH = 210     # A4
CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN


# ---------------------------------------------------------------------------
# Simple Markdown → FPDF renderer
# ---------------------------------------------------------------------------

class _PaperPDF(FPDF):
    def __init__(self, title: str):
        super().__init__()
        self.paper_title = title
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "I", FOOTER_SIZE)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, self.paper_title[:90], align="L")
        self.ln(2)
        self.set_draw_color(180, 180, 180)
        self.line(MARGIN, self.get_y(), PAGE_WIDTH - MARGIN, self.get_y())
        self.ln(4)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", FOOTER_SIZE)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f"Generated by CDLI Paper Agent · Page {self.page_no()}", align="C")


def _normalize_unicode(text: str) -> str:
    """
    Replace common Unicode characters that are not in the Latin-1 range
    (used by standard PDF fonts like Helvetica) with ASCII equivalents.
    """
    replacements = {
        "\u2014": " - ",  # em-dash
        "\u2013": "-",    # en-dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u00a0": " ",    # non-breaking space
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def _strip_inline_bold(text: str) -> tuple[str, bool]:
    """Return (clean_text, had_bold) for a line with **...** markers removed."""
    text = _normalize_unicode(text)
    had_bold = "**" in text
    clean = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    return clean, had_bold



def export_to_pdf(topic: str, markdown_text: str, output_path: Path) -> None:
    """
    Render *markdown_text* as a PDF and save it to *output_path*.
    """
    pdf = _PaperPDF(title=f"CDLI Research Paper: {topic}")
    pdf.add_page()

    # ── Title page block ──────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", TITLE_SIZE)
    pdf.multi_cell(0, 9, topic.title(), align="C")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", FOOTER_SIZE)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Cuneiform Digital Library Initiative (CDLI) · AI Research Agent", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)
    pdf.set_draw_color(60, 60, 60)
    pdf.line(MARGIN, pdf.get_y(), PAGE_WIDTH - MARGIN, pdf.get_y())
    pdf.ln(6)

    # ── Render Markdown body ──────────────────────────────────────────────────
    lines = markdown_text.splitlines()

    for line in lines:
        stripped = line.strip()

        # Skip the redundant top-level title if present (# Paper Title)
        if stripped.startswith("# "):
            continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            pdf.ln(2)
            pdf.set_draw_color(180, 180, 180)
            pdf.line(MARGIN, pdf.get_y(), PAGE_WIDTH - MARGIN, pdf.get_y())
            pdf.ln(4)
            continue

        # H2 heading
        if stripped.startswith("## "):
            pdf.ln(4)
            text, _ = _strip_inline_bold(stripped[3:])
            pdf.set_font("Helvetica", "B", H2_SIZE)
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(0, 8, text, fill=True)
            pdf.ln(5)
            continue

        # H3 heading
        if stripped.startswith("### "):
            pdf.ln(2)
            text, _ = _strip_inline_bold(stripped[4:])
            pdf.set_font("Helvetica", "B", H3_SIZE)
            pdf.cell(0, 7, text)
            pdf.ln(4)
            continue

        # Bullet point
        if stripped.startswith("- ") or stripped.startswith("* "):
            text, had_bold = _strip_inline_bold(stripped[2:])
            pdf.set_font("Helvetica", "B" if had_bold else "", BODY_SIZE)
            pdf.set_x(MARGIN + 5)
            pdf.multi_cell(CONTENT_WIDTH - 5, LINE_HEIGHT, f"•  {text}")
            continue

        # Blockquote note (from errors section)
        if stripped.startswith("> "):
            text, _ = _strip_inline_bold(stripped[2:])
            pdf.set_font("Helvetica", "I", BODY_SIZE)
            pdf.set_text_color(100, 100, 100)
            pdf.set_x(MARGIN + 5)
            pdf.multi_cell(CONTENT_WIDTH - 5, LINE_HEIGHT, text)
            pdf.set_text_color(0, 0, 0)
            continue

        # Inline code artifact citation  (`PXXXXXX — ...`)
        if stripped.startswith("`P") and stripped.endswith("`"):
            text = stripped.strip("`")
            pdf.set_font("Courier", "", BODY_SIZE)
            pdf.multi_cell(0, LINE_HEIGHT, text)
            pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # Empty line → paragraph break
        if stripped == "":
            pdf.ln(3)
            continue

        # Normal paragraph text (strip inline bold markers for rendering)
        text, had_bold = _strip_inline_bold(stripped)
        pdf.set_font("Helvetica", "B" if had_bold else "", BODY_SIZE)
        pdf.multi_cell(0, LINE_HEIGHT, text)
        pdf.ln(1)

    pdf.output(str(output_path))
